Width : 2256
Height : 1178
FileType : "Int32"
SubPlanes : 
  "Stagger" : 
    left : 148
    top : 38
    width : 1958
    height : 1116
  "Eff" : 
    left : 149
    top : 39
    width : 1957
    height : 1116
