using Pixels.Standard;
using Pixels.Standard.Processing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Media.Imaging;

/*

generated by T4Base.t4 v0.0.1
*/

namespace Pixels.Framework
{
    public static partial class WritableBitmapExtentions
    {
        #region field

        /**/

        #endregion

        #region [T4]ToWriteableBitmap24 

        /**/

        #endregion
    }
}




